# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Protocol

from dimos.spec.utils import Spec
from dimos.types.spatial_record import SpatialRecord, RecordType


class SpatialLandmarkMemorySpec(Spec, Protocol):
    """Protocol for spatial landmark memory. Implemented by SpatialLandmarkMemory."""

    def record(self, rec: SpatialRecord) -> str: ...
    def get_all(self) -> list[SpatialRecord]: ...
    def find_by_name(self, name: str) -> SpatialRecord | None: ...
    def search_by_name(self, query: str) -> list[SpatialRecord]: ...
    def find_nearest(self, x: float, y: float, radius: float) -> SpatialRecord | None: ...
    def query_by_text(self, query: str, limit: int) -> list[SpatialRecord]: ...
    def resolve_by_query(self, query: str) -> SpatialRecord | None: ...
    def query_by_type(self, record_type: RecordType) -> list[SpatialRecord]: ...
    def query_by_state(self, state: str) -> list[SpatialRecord]: ...
    def update_state(self, record_id: str, new_state: str) -> bool: ...
    def get_by_id(self, record_id: str) -> SpatialRecord | None: ...
    def save_snapshot(self, record_id: str, image_bytes: bytes) -> str | None: ...
    def save(self) -> bool: ...
    def load(self) -> bool: ...
    def clear_all(self) -> int: ...
