from . import Surface

def set_mode(size: tuple[int, int], flags: int = ..., depth: int = ...) -> Surface: ...
def set_caption(title: str, icontitle: str | None = ...) -> None: ...
def flip() -> None: ...
def update() -> None: ...
