from collections.abc import Sequence
from typing import overload

class _ScancodeWrapper(Sequence[bool]):
    @overload
    def __getitem__(self, index: int) -> bool: ...
    @overload
    def __getitem__(self, index: slice) -> Sequence[bool]: ...
    def __len__(self) -> int: ...

def get_pressed() -> _ScancodeWrapper: ...
def name(key: int) -> str: ...
