class Clock:
    def __init__(self) -> None: ...
    def tick(self, framerate: int = ...) -> int: ...
    def get_fps(self) -> float: ...

def get_ticks() -> int: ...
def wait(milliseconds: int) -> int: ...
