# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Emit the throwaway cargo crate that becomes the host binary."""

from __future__ import annotations

from collections.abc import Sequence
import json
from pathlib import Path
import re

from dimos.cli.bake.discovery import RegisteredModule
from dimos.cli.bake.errors import BakeError
from dimos.cli.bake.graph import Graph
from dimos.constants import DIMOS_PROJECT_ROOT

GENERATED_HEADER = "// GENERATED BY dimos bake. Do not edit."

_CARGO_TEMPLATE = """# GENERATED BY dimos bake. Do not edit.
[workspace]

[package]
name = "{host}"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "{host}"
path = "src/main.rs"

[dependencies]
{dependencies}

# Must match the workspace root's profiles or the shared target dir refingerprints.
[profile.release]
lto = "thin"
codegen-units = 1

[profile.release.package.{host}]
strip = "symbols"

[profile.dev]
debug = 0
"""

_MAIN_TEMPLATE = """{header}
use dimos_module::{{host_main, HostSpec, ModuleEntry}};

static MODULES: &[ModuleEntry] = &[
{entries}
];

static SUPPRESS: &[&str] = &[
{suppress}
];

static SPEC: HostSpec = HostSpec {{
    name: "{host}",
    modules: MODULES,
    default_topics: include_str!("default_topics.json"),
    default_suppress: SUPPRESS,
    default_qos: include_str!("default_qos.json"),
    graph_json: include_str!("graph.json"),
    graph_hash: "{fingerprint}",
}};

fn main() {{
    host_main(&SPEC)
}}
"""


def crate_dir(host: str, root: Path | None = None) -> Path:
    """Where the generated crate for `host` lives."""
    return (root or DIMOS_PROJECT_ROOT) / "build" / "dimos-bake" / host


def _dependencies(modules: Sequence[RegisteredModule], root: Path) -> str:
    lines = [f'dimos-module = {{ path = "{root / "native" / "rust" / "dimos-module"}" }}']
    # Keyed by crate: one crate can register several module ids, and a repeated
    # crate name is a duplicate key cargo refuses to parse.
    for crate_name, crate_path in dict.fromkeys((m.crate_name, m.crate_dir) for m in modules):
        lines.append(f'{crate_name} = {{ path = "{crate_path}" }}')
    return "\n".join(lines)


def _entries(modules: Sequence[RegisteredModule]) -> str:
    lines = []
    for module in modules:
        call = f'    ModuleEntry::new::<{module.rust_path}>("{module.id}")'
        if module.threads != 1:
            call += f".threads({module.threads})"
        lines.append(call + ",")
    return "\n".join(lines)


def render_cargo_toml(
    host: str, modules: Sequence[RegisteredModule], root: Path | None = None
) -> str:
    return _CARGO_TEMPLATE.format(
        host=host, dependencies=_dependencies(modules, root or DIMOS_PROJECT_ROOT)
    )


def render_main_rs(host: str, modules: Sequence[RegisteredModule], graph: Graph) -> str:
    suppress = "\n".join(f'    "{topic}",' for topic in graph.suppressed_topics())
    return _MAIN_TEMPLATE.format(
        header=GENERATED_HEADER,
        host=host,
        entries=_entries(modules),
        suppress=suppress,
        fingerprint=graph.fingerprint(),
    )


def check_host_name(host: str) -> None:
    """Reject a host name cargo would refuse as a package name."""
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", host):
        raise BakeError(
            f"`{host}` cannot name the host binary: cargo package names use "
            "letters, digits, `-` or `_` and cannot start with a digit"
        )


def generate_crate(
    host: str,
    modules: Sequence[RegisteredModule],
    graph: Graph,
    root: Path | None = None,
) -> Path:
    """Write the generated crate and return its directory."""
    check_host_name(host)
    root = root or DIMOS_PROJECT_ROOT
    directory = crate_dir(host, root)
    src = directory / "src"
    src.mkdir(parents=True, exist_ok=True)

    (directory / "Cargo.toml").write_text(render_cargo_toml(host, modules, root))
    # Check for workspace lock so we resolve to same dependencies
    root_lock = root / "Cargo.lock"
    if root_lock.exists():
        (directory / "Cargo.lock").write_text(root_lock.read_text())
    (src / "main.rs").write_text(render_main_rs(host, modules, graph))
    (src / "default_topics.json").write_text(json.dumps(graph.topics(), indent=2) + "\n")
    (src / "default_qos.json").write_text(json.dumps(graph.qos(), indent=2) + "\n")
    (src / "graph.json").write_text(json.dumps(graph.to_json(), indent=2) + "\n")
    return directory
