# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the generated host crate and the builder invocation."""

import json
from pathlib import Path

import pytest
import tomllib

from dimos.cli.bake.codegen import (
    check_host_name,
    generate_crate,
    render_cargo_toml,
    render_main_rs,
)
from dimos.cli.bake.errors import BakeError
from dimos.cli.bake.graph import build_graph
from dimos.cli.bake.test_graph import MAPPER, PLANNER, module
from dimos.constants import DIMOS_PROJECT_ROOT

GRAPH = build_graph("go2-nav", [MAPPER, PLANNER], suppress=["local_map"])


def test_cargo_toml_pins_absolute_paths_for_module_crates() -> None:
    toml = render_cargo_toml("go2-nav", [MAPPER, PLANNER], Path("/repo"))
    parsed = tomllib.loads(toml)
    assert '[[bin]]\nname = "go2-nav"' in toml
    assert 'dimos-module = { path = "/repo/native/rust/dimos-module" }' in toml
    assert 'crate-mapper = { path = "/crates/mapper" }' in toml
    assert toml.startswith("# GENERATED BY dimos bake")
    assert "[workspace]" in toml
    assert parsed["profile"]["release"]["package"]["go2-nav"]["strip"] == "symbols"
    assert "strip" not in parsed["profile"]["release"]


def test_the_generated_crate_reuses_the_workspace_profiles() -> None:
    root = tomllib.loads((DIMOS_PROJECT_ROOT / "Cargo.toml").read_text())
    generated = tomllib.loads(render_cargo_toml("go2-nav", [MAPPER, PLANNER], Path("/repo")))
    release = {k: v for k, v in generated["profile"]["release"].items() if k != "package"}
    assert release == root["profile"]["release"]
    assert generated["profile"]["dev"] == root["profile"]["dev"]


def test_main_rs_lists_entries_with_their_thread_counts() -> None:
    threaded = module("planner", PLANNER.inputs, PLANNER.outputs, threads=2)
    main = render_main_rs("go2-nav", [MAPPER, threaded], GRAPH)
    assert '    ModuleEntry::new::<mapper::module::Thing>("mapper"),' in main
    assert '    ModuleEntry::new::<planner::module::Thing>("planner").threads(2),' in main
    assert '    "dimos/local_map/sensor_msgs.PointCloud2",' in main
    assert main.startswith("// GENERATED BY dimos bake")
    assert 'name: "go2-nav",' in main
    assert 'include_str!("graph.json")' in main


def test_the_binary_carries_the_graph_stamp_its_config_is_checked_against() -> None:
    main = render_main_rs("go2-nav", [MAPPER, PLANNER], GRAPH)
    assert f'graph_hash: "{GRAPH.fingerprint()}",' in main


def test_rewiring_a_topic_changes_the_graph_stamp() -> None:
    remapped = build_graph(
        "go2-nav", [MAPPER, PLANNER], remaps={("planner", "path"): "route"}, suppress=["local_map"]
    )
    assert remapped.fingerprint() != GRAPH.fingerprint()


def test_generate_crate_writes_the_blobs_the_host_includes(tmp_path: Path) -> None:
    crate = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    assert crate == tmp_path / "build" / "dimos-bake" / "go2-nav"

    topics = json.loads((crate / "src" / "default_topics.json").read_text())
    assert topics["mapper"]["lidar"] == "dimos/lidar/sensor_msgs.PointCloud2"
    assert topics["planner"]["local_map"] == "dimos/local_map/sensor_msgs.PointCloud2"

    qos = json.loads((crate / "src" / "default_qos.json").read_text())
    assert qos["dimos/local_map/sensor_msgs.PointCloud2"]["congestion_control"] == "drop"

    graph = json.loads((crate / "src" / "graph.json").read_text())
    assert graph["host"] == "go2-nav"
    assert (crate / "Cargo.toml").exists()


def test_generate_crate_seeds_the_workspace_lock(tmp_path: Path) -> None:
    (tmp_path / "Cargo.lock").write_text('version = 4\n\n[[package]]\nname = "serde"\n')
    crate = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    assert (crate / "Cargo.lock").read_text() == (tmp_path / "Cargo.lock").read_text()


def test_generate_crate_is_idempotent(tmp_path: Path) -> None:
    first = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    before = (first / "src" / "main.rs").read_text()
    again = generate_crate("go2-nav", [MAPPER, PLANNER], GRAPH, tmp_path)
    assert (again / "src" / "main.rs").read_text() == before


def test_host_names_cargo_would_reject_are_refused() -> None:
    check_host_name("go2-nav")
    check_host_name("motion_host")
    for bad in ("go2-nav.bin", "2fast", "go2 nav", ""):
        with pytest.raises(BakeError, match="cannot name the host binary"):
            check_host_name(bad)
