// Regenerates the golden fixture vectors from protocol.ts.
//
// Run from web/:  deno run --allow-write=shared/fixtures shared/fixtures/gen.ts
//
// The vectors pin the byte-level protocol across the TS and Python codecs, so
// changes here are protocol changes and need review on both sides. Vector
// rules: no integral-valued floats (JS renders 1.0 as "1", Python as "1.0")
// and at least one non-ASCII string (pins ensure_ascii=False on the Python
// side). Message literals below are written in canonical field order - the
// same order the Python dataclasses declare.
//
// costmap_frames.json is NOT written here: its payloads are the Python
// encoder's zlib bytes (CompressionStream output differs byte-wise), so it is
// generated by `uv run python -m dimos.web.relay_bridge.gen_costmap_fixtures`.

import {
  CONTROL_CHANNEL,
  encodeControlFrame,
  encodeDataFrame,
  encodeDatagram,
  type FrameHeader,
  type Msg,
  PROTOCOL_VERSION,
} from "../protocol.ts";
import { ManifestError, parseManifest } from "../manifest.ts";

function b64(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}

// Shared by the pub vector and pub_tx_frame: the frame payload must be
// exactly the JSON.stringify of the pub's data (the relay's forwarding rule).
const pubData = { text: "Salut, robotule! β", urgency: 0.75 };

const controlMsgs: Record<string, Msg> = {
  hello_robot: {
    t: "hello",
    v: PROTOCOL_VERSION,
    role: "robot",
    robot: { id: "go2-lab", name: "Go2 Laborator β", model: "unitree-go2" },
    // A fully explicit (normalized) manifest, as the bridge emits it.
    manifest: {
      version: 1,
      channels: [
        {
          ch: "color_image",
          dir: "rx",
          encoding: "jpeg.v1",
          delivery: "latest",
          maxHz: 15.5,
          params: { quality: 75.5 },
          publish: "none",
          requiredScope: null,
        },
        {
          ch: "odom",
          dir: "rx",
          encoding: "pose.json.v1",
          delivery: "reliable",
          maxHz: 20.5,
          params: {},
          publish: "none",
          requiredScope: null,
        },
      ],
      panels: [
        { id: "p0", kind: "video", title: "Camera β", channels: ["color_image"], params: {} },
      ],
      layout: { row: ["p0"] },
      pages: [],
    },
  },
  hello_viewer: { t: "hello", v: PROTOCOL_VERSION, role: "viewer" },
  welcome: { t: "welcome", v: PROTOCOL_VERSION },
  ping: { t: "ping", n: 7, ts: 1752576000.5 },
  pong: { t: "pong", n: 7, ts: 1752576000.5 },
  error_version: {
    t: "error",
    code: "version_mismatch",
    message: `protocol v${PROTOCOL_VERSION} required, versiune neacceptată`,
  },
  robots_two: {
    t: "robots",
    robots: [
      { id: "go2-lab", name: "Go2 Laborator β", model: "unitree-go2" },
      { id: "arm-01", name: "Braț 01", model: "xarm7" },
    ],
  },
  robots_empty: { t: "robots", robots: [] },
  watch: { t: "watch", robotId: "go2-lab" },
  // Deliberately partial (un-normalized) manifest: the relay forwards the
  // robot's manifest verbatim, never normalizing it.
  manifest_reply: {
    t: "manifest",
    robotId: "go2-lab",
    manifest: {
      version: 1,
      channels: [{ ch: "odom", encoding: "pose.json.v1", delivery: "reliable", maxHz: 20.5 }],
      panels: [{ id: "pose", kind: "readout", title: "Poziție", channels: ["odom"] }],
      layout: "pose",
    },
  },
  // Watch reply for a robot that registered without a manifest.
  manifest_reply_bare: { t: "manifest", robotId: "arm-01" },
  sub: { t: "sub", ch: "color_image" },
  unsub: { t: "unsub", ch: "color_image" },
  subs_snapshot: { t: "subs", chs: ["color_image", "odom"], n: 3 },
  subs_empty: { t: "subs", chs: [], n: 4 },
  // Bare lease messages are the viewer-leg shapes (control stream); the
  // gen-stamped robot-bound forms are pinned in teleopMsgs below.
  teleop_start: { t: "teleop_start" },
  teleop_started: { t: "teleop_started" },
  teleop_stop: { t: "teleop_stop" },
  // Generic publish (W7): pub and pub_ack ride the viewer control stream
  // (pub_ack.id is the viewer's request id there). pub_nack is robot->relay
  // on a one-shot @control stream (id = the relay token); the relay maps it
  // to a correlated error like error_with_request_id.
  pub: {
    t: "pub",
    id: "s7k2β-1",
    ch: "human_input",
    data: pubData,
    clientTs: 1752576000.25,
  },
  pub_no_client_ts: { t: "pub", id: "s7k2β-2", ch: "human_input", data: [1.5, "β", true] },
  // data spans all of JSON: a top-level null must survive both mirrors'
  // encode paths (pins Python against exclude_none eating it).
  pub_null_data: { t: "pub", id: "s7k2β-3", ch: "human_input", data: null },
  pub_ack: {
    t: "pub_ack",
    id: "s7k2β-1",
    ch: "human_input",
    relayTs: 1752576000.5,
    bridgeTs: 1752576000.75,
  },
  pub_nack: { t: "pub_nack", id: "p3", code: "decode_failed", message: "text prea lung β" },
  error_with_request_id: {
    t: "error",
    code: "rate_limited",
    message: "publish peste limită β",
    requestId: "s7k2β-1",
  },
};

const teleopMsgs: Record<string, Msg> = {
  twist: { t: "twist", vx: 0.5, vy: 0.25, wz: -0.25, seq: 12, ts: 1752576000.5 },
  stop: { t: "stop", seq: 13, ts: 1752576000.5 },
  // Robot-bound forms: the relay stamps the lease generation.
  twist_gen: { t: "twist", vx: 0.5, vy: 0.25, wz: -0.25, seq: 12, ts: 1752576000.5, gen: 3 },
  stop_gen: { t: "stop", seq: 13, ts: 1752576000.5, gen: 3 },
  teleop_start_gen: { t: "teleop_start", gen: 3 },
  teleop_stop_gen: { t: "teleop_stop", gen: 3 },
};

const dataFrames: Record<string, { header: FrameHeader; payload: Uint8Array }> = {
  odom_reliable: {
    header: { ch: "odom", seq: 42, ts: 1752576000.5, delivery: "reliable" },
    payload: new TextEncoder().encode('{"x":1.5,"y":-2.5,"yaw":0.75}'),
  },
  image_latest_meta: {
    header: {
      ch: "color_image",
      seq: 100,
      ts: 1752576001.25,
      delivery: "latest",
      meta: { w: 320, h: 240 },
    },
    payload: Uint8Array.from({ length: 256 }, (_, i) => i),
  },
  empty_payload: {
    header: { ch: "odom", seq: 0, ts: 0.5, delivery: "reliable" },
    payload: new Uint8Array(0),
  },
  // v5 robot hello: an @control frame whose payload is the datagram encoding
  // of the hello message (pins the payload-reuses-datagram-encoding rule).
  control_hello: {
    header: { ch: CONTROL_CHANNEL, seq: 1, ts: 1752576000.5, delivery: "reliable" },
    payload: encodeDatagram(controlMsgs.hello_robot),
  },
  // Robot-bound subs snapshot as the relay's control carrier sends it: an
  // @control frame on the relay-opened reliable uni stream, same
  // payload-reuses-datagram-encoding rule as control_hello.
  control_subs: {
    header: { ch: CONTROL_CHANNEL, seq: 2, ts: 1752576000.75, delivery: "reliable" },
    payload: encodeDatagram(controlMsgs.subs_snapshot),
  },
  // Generic publish forwarded relay->robot (W7): the pub's JSON data as a
  // tx-channel data frame on the robot control carrier, provenance in meta
  // (meta.id is the relay-authored token, never the viewer's request id).
  pub_tx_frame: {
    header: {
      ch: "human_input",
      seq: 3,
      ts: 1752576000.5,
      delivery: "reliable",
      meta: { id: "p1", principal: "local", relayTs: 1752576000.5, clientTs: 1752576000.25 },
    },
    payload: new TextEncoder().encode(JSON.stringify(pubData)),
  },
};

// Manifest vectors: valid cases pin normalization, invalid cases pin the
// rejection code. Inputs are declared here (invalid ones cannot come from an
// encoder); outputs come from parseManifest, and test_manifest.py pins the
// Python mirror against them. Most inputs leave dir/params/title absent to
// pin the defaulting; chImageFull pins explicit-field round-trips.
const chOdom = { ch: "odom", encoding: "pose.json.v1", delivery: "reliable", maxHz: 20.5 };
const chImage = { ch: "color_image", encoding: "jpeg.v1", delivery: "latest", maxHz: 15.5 };
const chImageFull = {
  ch: "color_image",
  dir: "rx",
  encoding: "jpeg.v1",
  delivery: "latest",
  maxHz: 15.5,
  params: { quality: 75.5 },
};
const chCostmap = {
  ch: "global_costmap",
  encoding: "costmap.zlib.v1",
  delivery: "latest",
  maxHz: 5.5,
};
const chTwist = {
  ch: "tele_cmd_vel",
  dir: "tx",
  encoding: "twist.json.v1",
  delivery: "latest",
  maxHz: 15.5,
  params: { maxLinear: 0.85, maxAngular: 1.5, boost: 2.5, watchdogMs: 300.5 },
};
const chChat = {
  ch: "human_input",
  dir: "tx",
  encoding: "text.json.v1",
  delivery: "reliable",
  maxHz: 2.5,
  publish: "shared",
  requiredScope: "chat:send",
};
const chAgent = { ch: "agent", encoding: "chat.json.v1", delivery: "reliable", maxHz: 20.5 };
const chIdle = { ch: "agent_idle", encoding: "json.v1", delivery: "latest", maxHz: 20.5 };
const chAudio = {
  ch: "audio_in",
  dir: "tx",
  encoding: "audio.json.v1",
  delivery: "reliable",
  maxHz: 20.5,
  publish: "shared",
};
const pCamera = { id: "camera", kind: "video", channels: ["color_image"] };
const pChat = {
  id: "chat",
  kind: "chat",
  channels: ["human_input", "agent", "agent_idle", "audio_in"],
};
const pPose = { id: "pose", kind: "readout", channels: ["odom"] };
const longId = "x".repeat(65);
const manifestCases: Record<string, unknown> = {
  channels_only: { version: 1, channels: [chImage, chOdom] },
  empty: { version: 1, channels: [] },
  full: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [
      { ...pCamera, title: "Cameră față" },
      pPose,
      { id: "drive", kind: "joystick", channels: [] },
      { id: "aux", kind: "readout", channels: ["odom"] },
    ],
    layout: { row: [{ col: ["camera", "pose"], shares: [2.5, 1.5] }, "drive"] },
    pages: ["aux"],
  },
  extra_keys_ignored: {
    version: 1,
    channels: [{ ...chOdom, later: 1.5 }],
    panels: [{ ...pPose, future: true }],
    layout: { row: ["pose"], future: true },
    unknown_top_level: { x: 1 },
  },
  not_an_object: [1, 2],
  version_missing: { channels: [] },
  version_string: { version: "1", channels: [] },
  version_bool: { version: true, channels: [] },
  version_two: { version: 2, channels: [] },
  version_float: { version: 1.5, channels: [] },
  // The version gate runs before the channel shape check, so a future
  // manifest whose channels no longer parse still reports its version.
  version_before_channel_shape: { version: 2, channels: { alien: true } },
  missing_channels: { version: 1 },
  channel_bad_shape: { version: 1, channels: [{ ch: "odom" }] },
  bad_delivery: { version: 1, channels: [{ ...chOdom, delivery: "sometimes" }] },
  max_hz_string: { version: 1, channels: [{ ...chOdom, maxHz: "20" }] },
  max_hz_bool: { version: 1, channels: [{ ...chOdom, maxHz: true }] },
  empty_channel_id: { version: 1, channels: [{ ...chOdom, ch: "" }] },
  long_channel_id: { version: 1, channels: [{ ...chOdom, ch: longId }] },
  reserved_channel_id: { version: 1, channels: [{ ...chOdom, ch: CONTROL_CHANNEL }] },
  duplicate_channel_id: { version: 1, channels: [chOdom, { ...chOdom, encoding: "jpeg.v1" }] },
  empty_encoding: { version: 1, channels: [{ ...chOdom, encoding: "" }] },
  long_encoding: { version: 1, channels: [{ ...chOdom, encoding: longId }] },
  zero_max_hz: { version: 1, channels: [{ ...chOdom, maxHz: 0 }] },
  negative_max_hz: { version: 1, channels: [{ ...chOdom, maxHz: -2.5 }] },
  dir_tx_channel: { version: 1, channels: [{ ...chOdom, dir: "tx" }] },
  dir_invalid: { version: 1, channels: [{ ...chOdom, dir: "both" }] },
  dir_null: { version: 1, channels: [{ ...chOdom, dir: null }] },
  // Generic-publish rules (W7). The manifest layer accepts "exclusive"
  // (authoring and the bridge reject it until W8).
  publish_shared_tx: { version: 1, channels: [chChat] },
  publish_exclusive_tx: { version: 1, channels: [{ ...chChat, publish: "exclusive" }] },
  publish_none_roundtrip: { version: 1, channels: [{ ...chOdom, publish: "none" }] },
  required_scope_null_roundtrip: { version: 1, channels: [{ ...chChat, requiredScope: null }] },
  publish_on_rx: { version: 1, channels: [{ ...chOdom, publish: "shared" }] },
  publish_bad_value: { version: 1, channels: [{ ...chOdom, publish: "always" }] },
  publish_null: { version: 1, channels: [{ ...chOdom, publish: null }] },
  publish_shared_latest: { version: 1, channels: [{ ...chChat, delivery: "latest" }] },
  publish_shared_binary_encoding: { version: 1, channels: [{ ...chChat, encoding: "jpeg.v1" }] },
  scope_without_publish: { version: 1, channels: [{ ...chOdom, requiredScope: "chat:send" }] },
  scope_empty: { version: 1, channels: [{ ...chChat, requiredScope: "" }] },
  scope_too_long: { version: 1, channels: [{ ...chChat, requiredScope: longId }] },
  scope_not_string: { version: 1, channels: [{ ...chChat, requiredScope: 1.5 }] },
  // The rx-publish rule fires before the scope rules (document order).
  publish_rx_before_scope: {
    version: 1,
    channels: [{ ...chOdom, publish: "shared", requiredScope: "" }],
  },
  channel_params_roundtrip: { version: 1, channels: [chImageFull] },
  channel_params_not_object: { version: 1, channels: [{ ...chOdom, params: 1.5 }] },
  panels_not_list: { version: 1, channels: [chOdom], panels: {} },
  null_panels: { version: 1, channels: [chOdom], panels: null },
  panel_bad_shape: { version: 1, channels: [chOdom], panels: [{ id: "a" }] },
  panel_channels_not_strings: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "readout", channels: [1.5] }],
  },
  panel_title_roundtrip: {
    version: 1,
    channels: [chOdom],
    panels: [{ ...pPose, title: "Poziție" }],
  },
  panel_title_not_string: { version: 1, channels: [chOdom], panels: [{ ...pPose, title: 1.5 }] },
  panel_params_not_object: { version: 1, channels: [chOdom], panels: [{ ...pPose, params: [] }] },
  empty_panel_id: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "", kind: "readout", channels: [] }],
  },
  empty_panel_kind: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "", channels: [] }],
  },
  duplicate_panel_id: {
    version: 1,
    channels: [chOdom],
    panels: [
      { id: "a", kind: "readout", channels: [] },
      { id: "a", kind: "video", channels: [] },
    ],
  },
  panel_unknown_channel: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "a", kind: "video", channels: ["lidar"] }],
  },
  video_panel_no_channel: {
    version: 1,
    channels: [chImage],
    panels: [{ id: "cam", kind: "video", channels: [] }],
  },
  video_panel_two_channels: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [{ id: "cam", kind: "video", channels: ["color_image", "odom"] }],
  },
  video_panel_wrong_encoding: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "cam", kind: "video", channels: ["odom"] }],
  },
  video_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chImage, delivery: "reliable" }],
    panels: [{ id: "cam", kind: "video", channels: ["color_image"] }],
  },
  video_panel_tx_channel: {
    version: 1,
    channels: [{ ...chImage, dir: "tx" }],
    panels: [{ id: "cam", kind: "video", channels: ["color_image"] }],
  },
  map2d_panel_full: {
    version: 1,
    channels: [chCostmap, chOdom],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom"] }],
  },
  map2d_panel_no_pose: {
    version: 1,
    channels: [chCostmap],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_no_channel: {
    version: 1,
    channels: [chCostmap],
    panels: [{ id: "map", kind: "map2d", channels: [] }],
  },
  map2d_panel_three_channels: {
    version: 1,
    channels: [chCostmap, chOdom, chImage],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom", "color_image"] }],
  },
  map2d_panel_wrong_encoding: {
    version: 1,
    channels: [chOdom],
    panels: [{ id: "map", kind: "map2d", channels: ["odom"] }],
  },
  map2d_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chCostmap, delivery: "reliable" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_bad_pose: {
    version: 1,
    channels: [chCostmap, chImage],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "color_image"] }],
  },
  map2d_panel_tx_costmap: {
    version: 1,
    channels: [{ ...chCostmap, dir: "tx" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap"] }],
  },
  map2d_panel_tx_pose: {
    version: 1,
    channels: [chCostmap, { ...chOdom, dir: "tx" }],
    panels: [{ id: "map", kind: "map2d", channels: ["global_costmap", "odom"] }],
  },
  teleop_panel_valid: {
    version: 1,
    channels: [chTwist],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  teleop_panel_no_channel: {
    version: 1,
    channels: [chTwist],
    panels: [{ id: "drive", kind: "teleop", channels: [] }],
  },
  teleop_panel_two_channels: {
    version: 1,
    channels: [chTwist, chOdom],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel", "odom"] }],
  },
  teleop_panel_rx_channel: {
    version: 1,
    channels: [{ ...chTwist, dir: "rx" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  teleop_panel_wrong_encoding: {
    version: 1,
    channels: [{ ...chOdom, dir: "tx" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["odom"] }],
  },
  teleop_panel_wrong_delivery: {
    version: 1,
    channels: [{ ...chTwist, delivery: "reliable" }],
    panels: [{ id: "drive", kind: "teleop", channels: ["tele_cmd_vel"] }],
  },
  layout_single_panel: { version: 1, channels: [chOdom], panels: [pPose], layout: "pose" },
  layout_row_shares: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera", "pose"], shares: [2.5, 1.5] },
  },
  // Outer col has no shares: pins that absent shares stay absent in the
  // normalized tree (the equal-split default belongs to the renderer).
  layout_nested_tree: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose, { id: "drive", kind: "joystick", channels: [] }],
    layout: { col: [{ row: ["camera", "pose"], shares: [1.5, 2.5] }, "drive"] },
  },
  layout_null: { version: 1, channels: [chOdom], panels: [pPose], layout: null },
  layout_bad_node_type: { version: 1, channels: [chOdom], panels: [pPose], layout: 1.5 },
  layout_flat_list_rejected: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: ["pose"],
  },
  layout_row_and_col: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera"], col: ["pose"] },
  },
  layout_neither_row_nor_col: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { shares: [1.5] },
  },
  layout_children_not_array: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: "pose" },
  },
  layout_empty_children: { version: 1, channels: [chOdom], panels: [pPose], layout: { row: [] } },
  layout_nested_bad_node: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: [{ col: [2.5] }] },
  },
  layout_shares_not_array: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: "big" },
  },
  layout_shares_not_numbers: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: ["2"] },
  },
  layout_shares_bool: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [true] },
  },
  layout_shares_length_mismatch: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: { row: ["camera", "pose"], shares: [1.5] },
  },
  layout_share_zero: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [0] },
  },
  layout_share_negative: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [-1.5] },
  },
  layout_share_null: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: ["pose"], shares: [null] },
  },
  layout_unknown_panel: { version: 1, channels: [chOdom], panels: [pPose], layout: "ghost" },
  layout_deep_unknown_panel: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: { row: [{ col: ["ghost"] }] },
  },
  duplicate_layout_panel: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    layout: { row: ["camera", "camera"] },
  },
  duplicate_panel_across_layout_and_pages: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    layout: "camera",
    pages: ["camera"],
  },
  duplicate_panel_within_pages: {
    version: 1,
    channels: [chImage],
    panels: [pCamera],
    pages: ["camera", "camera"],
  },
  pages_only: { version: 1, channels: [chOdom], panels: [pPose], pages: ["pose"] },
  pages_and_layout: {
    version: 1,
    channels: [chImage, chOdom],
    panels: [pCamera, pPose],
    layout: "camera",
    pages: ["pose"],
  },
  unknown_page_panel: { version: 1, channels: [chOdom], panels: [pPose], pages: ["ghost"] },
  // Layout is validated before pages: the layout's unknown panel wins.
  layout_error_before_pages: {
    version: 1,
    channels: [chOdom],
    panels: [pPose],
    layout: "ghost",
    pages: ["phantom"],
  },
  pages_not_list: { version: 1, channels: [chOdom], panels: [pPose], pages: {} },
  pages_not_strings: { version: 1, channels: [chOdom], panels: [pPose], pages: [1.5] },
  pages_null: { version: 1, channels: [chOdom], panels: [pPose], pages: null },
  // Chat panel: text input (publish tx), messages, idle flag, push-to-talk
  // audio (publish tx), in that order.
  chat_panel: {
    version: 1,
    channels: [chChat, chAgent, chIdle, chAudio],
    panels: [pChat],
  },
  chat_panel_two_channels: {
    version: 1,
    channels: [chChat, chAgent],
    panels: [{ ...pChat, channels: ["human_input", "agent"] }],
  },
  // The pre-audio shape: three channels stopped being a chat panel.
  chat_panel_three_channels: {
    version: 1,
    channels: [chChat, chAgent, chIdle],
    panels: [{ ...pChat, channels: ["human_input", "agent", "agent_idle"] }],
  },
  chat_panel_input_not_publishable: {
    version: 1,
    channels: [
      { ch: "human_input", dir: "tx", encoding: "text.json.v1", delivery: "reliable", maxHz: 2.5 },
      chAgent,
      chIdle,
      chAudio,
    ],
    panels: [pChat],
  },
  chat_panel_messages_wrong_encoding: {
    version: 1,
    channels: [chChat, chOdom, chIdle, chAudio],
    panels: [{ ...pChat, channels: ["human_input", "odom", "agent_idle", "audio_in"] }],
  },
  chat_panel_idle_wrong_delivery: {
    version: 1,
    channels: [chChat, chAgent, { ...chIdle, delivery: "reliable" }, chAudio],
    panels: [pChat],
  },
  chat_panel_audio_not_publishable: {
    version: 1,
    channels: [
      chChat,
      chAgent,
      chIdle,
      { ch: "audio_in", dir: "tx", encoding: "audio.json.v1", delivery: "reliable", maxHz: 20.5 },
    ],
    panels: [pChat],
  },
};

const control = {
  vectors: Object.entries(controlMsgs).map(([name, message]) => ({
    name,
    message,
    b64: b64(encodeControlFrame(message)),
  })),
};

const datagrams = {
  vectors: Object.entries({ ...controlMsgs, ...teleopMsgs }).map(([name, message]) => ({
    name,
    message,
    b64: b64(encodeDatagram(message)),
  })),
};

const data = {
  vectors: Object.entries(dataFrames).map(([name, { header, payload }]) => ({
    name,
    header,
    payload_b64: b64(payload),
    frame_b64: b64(encodeDataFrame(header, payload)),
  })),
};

const manifests = {
  vectors: Object.entries(manifestCases).map(([name, data]) => {
    try {
      return { name, data, manifest: parseManifest(data) };
    } catch (e) {
      if (e instanceof ManifestError) return { name, data, error: e.code };
      throw e;
    }
  }),
};

const dir = new URL(".", import.meta.url);
for (
  const [file, obj] of [
    ["control_frames.json", control],
    ["datagrams.json", datagrams],
    ["data_frames.json", data],
    ["manifests.json", manifests],
  ] as const
) {
  await Deno.writeTextFile(new URL(file, dir), JSON.stringify(obj, null, 2) + "\n");
  console.log(`wrote ${file}`);
}
