from typing import Any

import numpy as np
import numpy.typing as npt

class ArmRobot:
    gravity_comp_factor: float
    is_running: bool
    is_estopped: bool
    gripper: Any
    _bus: Any
    _default_kp: npt.NDArray[np.floating[Any]]
    _default_kd: npt.NDArray[np.floating[Any]]
    _motor_chain: Any
    def start(
        self,
        initial_kp: npt.NDArray[np.floating[Any]] | None = ...,
        initial_kd: npt.NDArray[np.floating[Any]] | None = ...,
    ) -> None: ...
    def stop(self) -> None: ...
    def estop(self) -> None: ...
    def release(self) -> None: ...
    def get_robot_info(self) -> dict[str, Any]: ...
    def get_joint_state(self) -> dict[str, Any]: ...
    def command_joint_state(self, state: dict[str, Any]) -> None: ...
    def command_joint_pos(self, positions: npt.NDArray[np.floating[Any]]) -> None: ...
    def move_joints(
        self,
        positions: npt.NDArray[np.floating[Any]],
        speed: float = ...,
    ) -> None: ...
    def command_gripper(self, position: float) -> None: ...
    def get_gripper_pos(self) -> float | None: ...
    def set_gripper_free_drive(self, enabled: bool) -> None: ...
