name: ci
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  ci-complete:
    if: >
      github.event_name != 'pull_request' ||
      (
        github.event.pull_request.draft == false &&
        (
          github.event.action != 'labeled' ||
          github.event.label.name == 'automerge'
        )
      )
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: 'true'
